export interface producto{
        "ItemID":string,
        "CustomLabel":string,
        "Category":string,
        "StoreCategory":string,
        "Title": string,
        "ConditionID":'nuevo',
        "Marca":string,
        "MPN":string,
        "Product":string,
        "EAN":string,
        "PicURL":string,
        "Description":string,
        "Format":string,
        "Duration":string,
        "StartPrice":string,
        "Quantity":string,
        "Location": string,
        "ShippingProfileName":string,
        "ReturnProfileName": string,
        "PaymentProfileName":string,
        "Relationship":string,
        "RelationshipDetails":string
}
